name: Build Godot Project

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  export_web:
    name: Export
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Export Game
        id: export
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.2/Godot_v3.5.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          use_preset_export_path: true
          use_godot_3: true
          export_debug: false

      - name: Upload web build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_KEY }}
          gameData: ./bin/web/web.zip
          itchUsername: arya-s
          itchGameId: postman
          buildChannel: html5

      - name: Upload windows build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_KEY }}
          gameData: ./bin/win/win.zip
          itchUsername: arya-s
          itchGameId: postman
          buildChannel: windows

      - name: Archive the builds
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.export.outputs.archive_directory }}/*
